/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "machine.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Envelope, Envelope, 2)


PB_BIND(ShowPage, ShowPage, AUTO)


PB_BIND(SetText, SetText, AUTO)


PB_BIND(SetColor, SetColor, AUTO)


PB_BIND(SetVisible, SetVisible, AUTO)


PB_BIND(SetValue, SetValue, AUTO)


PB_BIND(SetBatch, SetBatch, 2)


PB_BIND(ButtonEvent, ButtonEvent, AUTO)


PB_BIND(InputEvent, InputEvent, AUTO)


PB_BIND(Heartbeat, Heartbeat, AUTO)



