/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "machine.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Envelope, Envelope, 2)


PB_BIND(ShowPage, ShowPage, AUTO)


PB_BIND(SetText, SetText, AUTO)


PB_BIND(SetColor, SetColor, AUTO)


PB_BIND(SetVisible, SetVisible, AUTO)


PB_BIND(SetValue, SetValue, AUTO)


PB_BIND(SetBatch, SetBatch, 2)


PB_BIND(SetElementAttribute, SetElementAttribute, AUTO)


PB_BIND(ButtonEvent, ButtonEvent, AUTO)


PB_BIND(InputEvent, InputEvent, AUTO)


PB_BIND(Heartbeat, Heartbeat, AUTO)


PB_BIND(ColorState, ColorState, AUTO)


PB_BIND(PageElementState, PageElementState, AUTO)


PB_BIND(DeviceInfo, DeviceInfo, AUTO)


PB_BIND(Hello, Hello, AUTO)


PB_BIND(RequestDeviceInfo, RequestDeviceInfo, AUTO)


PB_BIND(RequestCurrentPage, RequestCurrentPage, AUTO)


PB_BIND(CurrentPage, CurrentPage, AUTO)


PB_BIND(RequestPageState, RequestPageState, AUTO)


PB_BIND(PageState, PageState, 2)


PB_BIND(RequestElementState, RequestElementState, AUTO)


PB_BIND(ElementState, ElementState, AUTO)


PB_BIND(RequestElementAttribute, RequestElementAttribute, AUTO)


PB_BIND(ElementAttributeState, ElementAttributeState, AUTO)











