/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MACHINE_PB_H_INCLUDED
#define PB_MACHINE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Поддерживаемые атрибуты элемента (точечный set/get). */
typedef enum _ElementAttribute {
    ElementAttribute_ELEMENT_ATTRIBUTE_UNKNOWN = 0,
    ElementAttribute_ELEMENT_ATTRIBUTE_POSITION_WIDTH = 1,
    ElementAttribute_ELEMENT_ATTRIBUTE_POSITION_HEIGHT = 2,
    ElementAttribute_ELEMENT_ATTRIBUTE_BACKGROUND_COLOR = 3,
    ElementAttribute_ELEMENT_ATTRIBUTE_BORDER_COLOR = 4,
    ElementAttribute_ELEMENT_ATTRIBUTE_BORDER_WIDTH = 5,
    ElementAttribute_ELEMENT_ATTRIBUTE_TEXT_COLOR = 6,
    ElementAttribute_ELEMENT_ATTRIBUTE_TEXT_FONT = 7,
    ElementAttribute_ELEMENT_ATTRIBUTE_VISIBLE = 8, /* bool */
    ElementAttribute_ELEMENT_ATTRIBUTE_TEXT = 9, /* string */
    ElementAttribute_ELEMENT_ATTRIBUTE_VALUE = 10, /* int32 (slider/bar/checkbox/switch) */
    ElementAttribute_ELEMENT_ATTRIBUTE_X = 11, /* int32 */
    ElementAttribute_ELEMENT_ATTRIBUTE_Y = 12 /* int32 */
} ElementAttribute;

/* Типизированный id шрифта для text.font. */
typedef enum _ElementFont {
    ElementFont_ELEMENT_FONT_UNKNOWN = 0,
    ElementFont_ELEMENT_FONT_UI_M18 = 1,
    ElementFont_ELEMENT_FONT_UI_M20 = 2,
    ElementFont_ELEMENT_FONT_UI_M24 = 3,
    ElementFont_ELEMENT_FONT_UI_M70 = 4
} ElementFont;

/* Причина изменения атрибута в AttributeChanged (экран → бэк). */
typedef enum _AttributeChangeReason {
    AttributeChangeReason_REASON_UNKNOWN = 0,
    AttributeChangeReason_REASON_COMMAND_APPLIED = 1, /* ACK на SetElementAttribute */
    AttributeChangeReason_REASON_LAYOUT = 2, /* LVGL сам пересчитал layout */
    AttributeChangeReason_REASON_USER_INPUT = 3, /* пользователь ввёл/изменил */
    AttributeChangeReason_REASON_ANIMATION = 4 /* итог анимации */
} AttributeChangeReason;

/* Тип кнопочного события. */
typedef enum _ButtonAction {
    ButtonAction_CLICK = 0,
    ButtonAction_PUSH = 1,
    ButtonAction_POP = 2,
    ButtonAction_REPEAT = 3
} ButtonAction;

/* Struct definitions */
/* Показать страницу по ID.
 session_id — эпоха навигации, инкрементируется бэком при каждом переходе.
 Все последующие сообщения по этой странице (SetElementAttribute,
 PageSnapshot, AttributeChanged, ButtonEvent, InputEvent) должны нести
 соответствующий session_id. Устаревшие сообщения получатель игнорирует. */
typedef struct _ShowPage {
    uint32_t page_id;
    uint32_t session_id;
} ShowPage;

/* Точечная запись одного атрибута элемента.
 request_id — для ACK-сопоставления: экран в ответ пришлёт
 AttributeChanged с in_reply_to_request = request_id и reason =
 REASON_COMMAND_APPLIED. 0 означает "без ответа" (fire-and-forget).
 session_id — эпоха страницы. 0 допустим для legacy-совместимости
 (получатель не проверяет). */
typedef struct _SetElementAttribute {
    uint32_t element_id;
    ElementAttribute attribute;
    pb_size_t which_value;
    union {
        int32_t int_value;
        uint32_t color_value; /* RGB888 */
        ElementFont font_value;
        bool bool_value;
        char string_value[48];
    } value;
    uint32_t request_id;
    uint32_t session_id;
} SetElementAttribute;

/* Универсальное значение одного атрибута.
 Переиспользуется в PageSnapshot и AttributeChanged как кирпичик. */
typedef struct _ElementAttributeValue {
    ElementAttribute attribute;
    pb_size_t which_value;
    union {
        int32_t int_value;
        uint32_t color_value; /* RGB888 */
        ElementFont font_value;
        bool bool_value;
        char string_value[48];
    } value;
} ElementAttributeValue;

/* Снимок состояния одного элемента в рамках PageSnapshot. */
typedef struct _ElementSnapshot {
    uint32_t element_id;
    pb_size_t attributes_count;
    ElementAttributeValue attributes[10];
} ElementSnapshot;

/* Полный снимок состояния страницы (экран → бэк).
 Отправляется экраном в ответ на ShowPage с тем же session_id.
 Бэк применяет snapshot как каноничное состояние страницы. */
typedef struct _PageSnapshot {
    uint32_t session_id;
    uint32_t page_id;
    pb_size_t elements_count;
    ElementSnapshot elements[16];
} PageSnapshot;

/* Точечная дельта изменения атрибута (экран → бэк).
 Используется и как ACK команды (reason = REASON_COMMAND_APPLIED,
 in_reply_to_request = request_id из SetElementAttribute),
 и как спонтанное сообщение о layout/user input (in_reply_to_request = 0). */
typedef struct _AttributeChanged {
    uint32_t session_id;
    uint32_t page_id;
    uint32_t element_id;
    bool has_value;
    ElementAttributeValue value;
    AttributeChangeReason reason;
    uint32_t in_reply_to_request; /* 0 если спонтанно */
} AttributeChanged;

/* Нажатие кнопки или другого интерактивного элемента.
 session_id — эпоха страницы на момент события. Бэк игнорирует,
 если уже перешёл на следующую страницу. */
typedef struct _ButtonEvent {
    uint32_t element_id;
    uint32_t page_id; /* с какой страницы пришло событие */
    ButtonAction action;
    uint32_t session_id;
} ButtonEvent;

/* Ввод данных пользователем (числовой input, поле текста).
 session_id — эпоха страницы на момент события. */
typedef struct _InputEvent {
    uint32_t element_id;
    uint32_t page_id;
    pb_size_t which_value;
    union {
        int32_t int_value;
        char string_value[32]; /* макс. 64 символа (см. machine.options) */
    } value;
    uint32_t session_id;
} InputEvent;

/* Heartbeat — обе стороны шлют периодически для контроля связи */
typedef struct _Heartbeat {
    uint32_t uptime_ms; /* время работы отправителя в мс */
} Heartbeat;

/* Идентификация и capability screen client. */
typedef struct _DeviceInfo {
    uint32_t protocol_version;
    char fw_version[24];
    char ui_version[24];
    char screen_type[24];
    char client_type[24];
    char device_id[32];
    char instance_id[32];
    uint32_t capabilities; /* bit flags */
} DeviceInfo;

/* Асинхронное приветствие screen client (например, после reconnect). */
typedef struct _Hello {
    bool has_device_info;
    DeviceInfo device_info;
} Hello;

typedef struct _RequestDeviceInfo {
    uint32_t request_id;
} RequestDeviceInfo;

typedef struct _RequestCurrentPage {
    uint32_t request_id;
} RequestCurrentPage;

typedef struct _CurrentPage {
    uint32_t request_id;
    uint32_t page_id;
} CurrentPage;

/* Запрос одного точечного атрибута элемента. */
typedef struct _RequestElementAttribute {
    uint32_t request_id;
    uint32_t page_id;
    uint32_t element_id;
    ElementAttribute attribute;
} RequestElementAttribute;

/* Ответ со значением одного атрибута элемента. */
typedef struct _ElementAttributeState {
    uint32_t request_id;
    uint32_t page_id;
    uint32_t element_id;
    ElementAttribute attribute;
    bool found;
    pb_size_t which_value;
    union {
        int32_t int_value;
        uint32_t color_value; /* RGB888 */
        ElementFont font_value;
    } value;
} ElementAttributeState;

/* Обёртка — всегда передаётся как payload в FrameCodec */
typedef struct _Envelope {
    pb_size_t which_payload;
    union {
        ShowPage show_page; /* показать страницу */
        ButtonEvent button_event; /* нажатие кнопки (экран → контроллер) */
        InputEvent input_event; /* ввод значения пользователем */
        Heartbeat heartbeat; /* watchdog / детекция разрыва */
        /* ---- Service layer (metadata / request-response) ---- */
        Hello hello; /* screen client может слать при connect/reconnect */
        RequestDeviceInfo request_device_info; /* backend -> screen */
        DeviceInfo device_info; /* screen -> backend (response или async info) */
        RequestCurrentPage request_current_page; /* backend -> screen */
        CurrentPage current_page; /* screen -> backend */
        SetElementAttribute set_element_attribute; /* точечная запись style/layout атрибута */
        /* reserved: tag 20 (set_element_attribute_batch) — удалён, не переиспользовать. */
        RequestElementAttribute request_element_attribute; /* backend -> screen */
        ElementAttributeState element_attribute_state; /* screen -> backend */
        PageSnapshot page_snapshot; /* screen -> backend (полный слепок страницы) */
        AttributeChanged attribute_changed; /* screen -> backend (дельта + ACK команды) */
    } payload;
} Envelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ElementAttribute_MIN ElementAttribute_ELEMENT_ATTRIBUTE_UNKNOWN
#define _ElementAttribute_MAX ElementAttribute_ELEMENT_ATTRIBUTE_Y
#define _ElementAttribute_ARRAYSIZE ((ElementAttribute)(ElementAttribute_ELEMENT_ATTRIBUTE_Y+1))

#define _ElementFont_MIN ElementFont_ELEMENT_FONT_UNKNOWN
#define _ElementFont_MAX ElementFont_ELEMENT_FONT_UI_M70
#define _ElementFont_ARRAYSIZE ((ElementFont)(ElementFont_ELEMENT_FONT_UI_M70+1))

#define _AttributeChangeReason_MIN AttributeChangeReason_REASON_UNKNOWN
#define _AttributeChangeReason_MAX AttributeChangeReason_REASON_ANIMATION
#define _AttributeChangeReason_ARRAYSIZE ((AttributeChangeReason)(AttributeChangeReason_REASON_ANIMATION+1))

#define _ButtonAction_MIN ButtonAction_CLICK
#define _ButtonAction_MAX ButtonAction_REPEAT
#define _ButtonAction_ARRAYSIZE ((ButtonAction)(ButtonAction_REPEAT+1))



#define SetElementAttribute_attribute_ENUMTYPE ElementAttribute
#define SetElementAttribute_value_font_value_ENUMTYPE ElementFont

#define ElementAttributeValue_attribute_ENUMTYPE ElementAttribute
#define ElementAttributeValue_value_font_value_ENUMTYPE ElementFont



#define AttributeChanged_reason_ENUMTYPE AttributeChangeReason

#define ButtonEvent_action_ENUMTYPE ButtonAction








#define RequestElementAttribute_attribute_ENUMTYPE ElementAttribute

#define ElementAttributeState_attribute_ENUMTYPE ElementAttribute
#define ElementAttributeState_value_font_value_ENUMTYPE ElementFont


/* Initializer values for message structs */
#define Envelope_init_default                    {0, {ShowPage_init_default}}
#define ShowPage_init_default                    {0, 0}
#define SetElementAttribute_init_default         {0, _ElementAttribute_MIN, 0, {0}, 0, 0}
#define ElementAttributeValue_init_default       {_ElementAttribute_MIN, 0, {0}}
#define ElementSnapshot_init_default             {0, 0, {ElementAttributeValue_init_default, ElementAttributeValue_init_default, ElementAttributeValue_init_default, ElementAttributeValue_init_default, ElementAttributeValue_init_default, ElementAttributeValue_init_default, ElementAttributeValue_init_default, ElementAttributeValue_init_default, ElementAttributeValue_init_default, ElementAttributeValue_init_default}}
#define PageSnapshot_init_default                {0, 0, 0, {ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default, ElementSnapshot_init_default}}
#define AttributeChanged_init_default            {0, 0, 0, false, ElementAttributeValue_init_default, _AttributeChangeReason_MIN, 0}
#define ButtonEvent_init_default                 {0, 0, _ButtonAction_MIN, 0}
#define InputEvent_init_default                  {0, 0, 0, {0}, 0}
#define Heartbeat_init_default                   {0}
#define DeviceInfo_init_default                  {0, "", "", "", "", "", "", 0}
#define Hello_init_default                       {false, DeviceInfo_init_default}
#define RequestDeviceInfo_init_default           {0}
#define RequestCurrentPage_init_default          {0}
#define CurrentPage_init_default                 {0, 0}
#define RequestElementAttribute_init_default     {0, 0, 0, _ElementAttribute_MIN}
#define ElementAttributeState_init_default       {0, 0, 0, _ElementAttribute_MIN, 0, 0, {0}}
#define Envelope_init_zero                       {0, {ShowPage_init_zero}}
#define ShowPage_init_zero                       {0, 0}
#define SetElementAttribute_init_zero            {0, _ElementAttribute_MIN, 0, {0}, 0, 0}
#define ElementAttributeValue_init_zero          {_ElementAttribute_MIN, 0, {0}}
#define ElementSnapshot_init_zero                {0, 0, {ElementAttributeValue_init_zero, ElementAttributeValue_init_zero, ElementAttributeValue_init_zero, ElementAttributeValue_init_zero, ElementAttributeValue_init_zero, ElementAttributeValue_init_zero, ElementAttributeValue_init_zero, ElementAttributeValue_init_zero, ElementAttributeValue_init_zero, ElementAttributeValue_init_zero}}
#define PageSnapshot_init_zero                   {0, 0, 0, {ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero, ElementSnapshot_init_zero}}
#define AttributeChanged_init_zero               {0, 0, 0, false, ElementAttributeValue_init_zero, _AttributeChangeReason_MIN, 0}
#define ButtonEvent_init_zero                    {0, 0, _ButtonAction_MIN, 0}
#define InputEvent_init_zero                     {0, 0, 0, {0}, 0}
#define Heartbeat_init_zero                      {0}
#define DeviceInfo_init_zero                     {0, "", "", "", "", "", "", 0}
#define Hello_init_zero                          {false, DeviceInfo_init_zero}
#define RequestDeviceInfo_init_zero              {0}
#define RequestCurrentPage_init_zero             {0}
#define CurrentPage_init_zero                    {0, 0}
#define RequestElementAttribute_init_zero        {0, 0, 0, _ElementAttribute_MIN}
#define ElementAttributeState_init_zero          {0, 0, 0, _ElementAttribute_MIN, 0, 0, {0}}

/* Field tags (for use in manual encoding/decoding) */
#define ShowPage_page_id_tag                     1
#define ShowPage_session_id_tag                  2
#define SetElementAttribute_element_id_tag       1
#define SetElementAttribute_attribute_tag        2
#define SetElementAttribute_int_value_tag        3
#define SetElementAttribute_color_value_tag      4
#define SetElementAttribute_font_value_tag       5
#define SetElementAttribute_bool_value_tag       8
#define SetElementAttribute_string_value_tag     9
#define SetElementAttribute_request_id_tag       6
#define SetElementAttribute_session_id_tag       7
#define ElementAttributeValue_attribute_tag      1
#define ElementAttributeValue_int_value_tag      2
#define ElementAttributeValue_color_value_tag    3
#define ElementAttributeValue_font_value_tag     4
#define ElementAttributeValue_bool_value_tag     5
#define ElementAttributeValue_string_value_tag   6
#define ElementSnapshot_element_id_tag           1
#define ElementSnapshot_attributes_tag           2
#define PageSnapshot_session_id_tag              1
#define PageSnapshot_page_id_tag                 2
#define PageSnapshot_elements_tag                3
#define AttributeChanged_session_id_tag          1
#define AttributeChanged_page_id_tag             2
#define AttributeChanged_element_id_tag          3
#define AttributeChanged_value_tag               4
#define AttributeChanged_reason_tag              5
#define AttributeChanged_in_reply_to_request_tag 6
#define ButtonEvent_element_id_tag               1
#define ButtonEvent_page_id_tag                  2
#define ButtonEvent_action_tag                   3
#define ButtonEvent_session_id_tag               4
#define InputEvent_element_id_tag                1
#define InputEvent_page_id_tag                   2
#define InputEvent_int_value_tag                 3
#define InputEvent_string_value_tag              4
#define InputEvent_session_id_tag                5
#define Heartbeat_uptime_ms_tag                  1
#define DeviceInfo_protocol_version_tag          1
#define DeviceInfo_fw_version_tag                2
#define DeviceInfo_ui_version_tag                3
#define DeviceInfo_screen_type_tag               4
#define DeviceInfo_client_type_tag               5
#define DeviceInfo_device_id_tag                 6
#define DeviceInfo_instance_id_tag               7
#define DeviceInfo_capabilities_tag              8
#define Hello_device_info_tag                    1
#define RequestDeviceInfo_request_id_tag         1
#define RequestCurrentPage_request_id_tag        1
#define CurrentPage_request_id_tag               1
#define CurrentPage_page_id_tag                  2
#define RequestElementAttribute_request_id_tag   1
#define RequestElementAttribute_page_id_tag      2
#define RequestElementAttribute_element_id_tag   3
#define RequestElementAttribute_attribute_tag    4
#define ElementAttributeState_request_id_tag     1
#define ElementAttributeState_page_id_tag        2
#define ElementAttributeState_element_id_tag     3
#define ElementAttributeState_attribute_tag      4
#define ElementAttributeState_found_tag          5
#define ElementAttributeState_int_value_tag      6
#define ElementAttributeState_color_value_tag    7
#define ElementAttributeState_font_value_tag     8
#define Envelope_show_page_tag                   1
#define Envelope_button_event_tag                7
#define Envelope_input_event_tag                 8
#define Envelope_heartbeat_tag                   9
#define Envelope_hello_tag                       10
#define Envelope_request_device_info_tag         11
#define Envelope_device_info_tag                 12
#define Envelope_request_current_page_tag        13
#define Envelope_current_page_tag                14
#define Envelope_set_element_attribute_tag       19
#define Envelope_request_element_attribute_tag   21
#define Envelope_element_attribute_state_tag     22
#define Envelope_page_snapshot_tag               23
#define Envelope_attribute_changed_tag           24

/* Struct field encoding specification for nanopb */
#define Envelope_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,show_page,payload.show_page),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,button_event,payload.button_event),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,input_event,payload.input_event),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,heartbeat,payload.heartbeat),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,hello,payload.hello),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,request_device_info,payload.request_device_info),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,device_info,payload.device_info),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,request_current_page,payload.request_current_page),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,current_page,payload.current_page),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_element_attribute,payload.set_element_attribute),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,request_element_attribute,payload.request_element_attribute),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,element_attribute_state,payload.element_attribute_state),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,page_snapshot,payload.page_snapshot),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,attribute_changed,payload.attribute_changed),  24)
#define Envelope_CALLBACK NULL
#define Envelope_DEFAULT NULL
#define Envelope_payload_show_page_MSGTYPE ShowPage
#define Envelope_payload_button_event_MSGTYPE ButtonEvent
#define Envelope_payload_input_event_MSGTYPE InputEvent
#define Envelope_payload_heartbeat_MSGTYPE Heartbeat
#define Envelope_payload_hello_MSGTYPE Hello
#define Envelope_payload_request_device_info_MSGTYPE RequestDeviceInfo
#define Envelope_payload_device_info_MSGTYPE DeviceInfo
#define Envelope_payload_request_current_page_MSGTYPE RequestCurrentPage
#define Envelope_payload_current_page_MSGTYPE CurrentPage
#define Envelope_payload_set_element_attribute_MSGTYPE SetElementAttribute
#define Envelope_payload_request_element_attribute_MSGTYPE RequestElementAttribute
#define Envelope_payload_element_attribute_state_MSGTYPE ElementAttributeState
#define Envelope_payload_page_snapshot_MSGTYPE PageSnapshot
#define Envelope_payload_attribute_changed_MSGTYPE AttributeChanged

#define ShowPage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   page_id,           1) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        2)
#define ShowPage_CALLBACK NULL
#define ShowPage_DEFAULT NULL

#define SetElementAttribute_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        1) \
X(a, STATIC,   SINGULAR, UENUM,    attribute,         2) \
X(a, STATIC,   ONEOF,    INT32,    (value,int_value,value.int_value),   3) \
X(a, STATIC,   ONEOF,    UINT32,   (value,color_value,value.color_value),   4) \
X(a, STATIC,   ONEOF,    UENUM,    (value,font_value,value.font_value),   5) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        6) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        7) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),   8) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,value.string_value),   9)
#define SetElementAttribute_CALLBACK NULL
#define SetElementAttribute_DEFAULT NULL

#define ElementAttributeValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    attribute,         1) \
X(a, STATIC,   ONEOF,    INT32,    (value,int_value,value.int_value),   2) \
X(a, STATIC,   ONEOF,    UINT32,   (value,color_value,value.color_value),   3) \
X(a, STATIC,   ONEOF,    UENUM,    (value,font_value,value.font_value),   4) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),   5) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,value.string_value),   6)
#define ElementAttributeValue_CALLBACK NULL
#define ElementAttributeValue_DEFAULT NULL

#define ElementSnapshot_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        1) \
X(a, STATIC,   REPEATED, MESSAGE,  attributes,        2)
#define ElementSnapshot_CALLBACK NULL
#define ElementSnapshot_DEFAULT NULL
#define ElementSnapshot_attributes_MSGTYPE ElementAttributeValue

#define PageSnapshot_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   page_id,           2) \
X(a, STATIC,   REPEATED, MESSAGE,  elements,          3)
#define PageSnapshot_CALLBACK NULL
#define PageSnapshot_DEFAULT NULL
#define PageSnapshot_elements_MSGTYPE ElementSnapshot

#define AttributeChanged_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   page_id,           2) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             4) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            5) \
X(a, STATIC,   SINGULAR, UINT32,   in_reply_to_request,   6)
#define AttributeChanged_CALLBACK NULL
#define AttributeChanged_DEFAULT NULL
#define AttributeChanged_value_MSGTYPE ElementAttributeValue

#define ButtonEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   page_id,           2) \
X(a, STATIC,   SINGULAR, UENUM,    action,            3) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        4)
#define ButtonEvent_CALLBACK NULL
#define ButtonEvent_DEFAULT NULL

#define InputEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   page_id,           2) \
X(a, STATIC,   ONEOF,    INT32,    (value,int_value,value.int_value),   3) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,value.string_value),   4) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        5)
#define InputEvent_CALLBACK NULL
#define InputEvent_DEFAULT NULL

#define Heartbeat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_ms,         1)
#define Heartbeat_CALLBACK NULL
#define Heartbeat_DEFAULT NULL

#define DeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, STRING,   fw_version,        2) \
X(a, STATIC,   SINGULAR, STRING,   ui_version,        3) \
X(a, STATIC,   SINGULAR, STRING,   screen_type,       4) \
X(a, STATIC,   SINGULAR, STRING,   client_type,       5) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         6) \
X(a, STATIC,   SINGULAR, STRING,   instance_id,       7) \
X(a, STATIC,   SINGULAR, UINT32,   capabilities,      8)
#define DeviceInfo_CALLBACK NULL
#define DeviceInfo_DEFAULT NULL

#define Hello_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       1)
#define Hello_CALLBACK NULL
#define Hello_DEFAULT NULL
#define Hello_device_info_MSGTYPE DeviceInfo

#define RequestDeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1)
#define RequestDeviceInfo_CALLBACK NULL
#define RequestDeviceInfo_DEFAULT NULL

#define RequestCurrentPage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1)
#define RequestCurrentPage_CALLBACK NULL
#define RequestCurrentPage_DEFAULT NULL

#define CurrentPage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   page_id,           2)
#define CurrentPage_CALLBACK NULL
#define CurrentPage_DEFAULT NULL

#define RequestElementAttribute_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   page_id,           2) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        3) \
X(a, STATIC,   SINGULAR, UENUM,    attribute,         4)
#define RequestElementAttribute_CALLBACK NULL
#define RequestElementAttribute_DEFAULT NULL

#define ElementAttributeState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   page_id,           2) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        3) \
X(a, STATIC,   SINGULAR, UENUM,    attribute,         4) \
X(a, STATIC,   SINGULAR, BOOL,     found,             5) \
X(a, STATIC,   ONEOF,    INT32,    (value,int_value,value.int_value),   6) \
X(a, STATIC,   ONEOF,    UINT32,   (value,color_value,value.color_value),   7) \
X(a, STATIC,   ONEOF,    UENUM,    (value,font_value,value.font_value),   8)
#define ElementAttributeState_CALLBACK NULL
#define ElementAttributeState_DEFAULT NULL

extern const pb_msgdesc_t Envelope_msg;
extern const pb_msgdesc_t ShowPage_msg;
extern const pb_msgdesc_t SetElementAttribute_msg;
extern const pb_msgdesc_t ElementAttributeValue_msg;
extern const pb_msgdesc_t ElementSnapshot_msg;
extern const pb_msgdesc_t PageSnapshot_msg;
extern const pb_msgdesc_t AttributeChanged_msg;
extern const pb_msgdesc_t ButtonEvent_msg;
extern const pb_msgdesc_t InputEvent_msg;
extern const pb_msgdesc_t Heartbeat_msg;
extern const pb_msgdesc_t DeviceInfo_msg;
extern const pb_msgdesc_t Hello_msg;
extern const pb_msgdesc_t RequestDeviceInfo_msg;
extern const pb_msgdesc_t RequestCurrentPage_msg;
extern const pb_msgdesc_t CurrentPage_msg;
extern const pb_msgdesc_t RequestElementAttribute_msg;
extern const pb_msgdesc_t ElementAttributeState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Envelope_fields &Envelope_msg
#define ShowPage_fields &ShowPage_msg
#define SetElementAttribute_fields &SetElementAttribute_msg
#define ElementAttributeValue_fields &ElementAttributeValue_msg
#define ElementSnapshot_fields &ElementSnapshot_msg
#define PageSnapshot_fields &PageSnapshot_msg
#define AttributeChanged_fields &AttributeChanged_msg
#define ButtonEvent_fields &ButtonEvent_msg
#define InputEvent_fields &InputEvent_msg
#define Heartbeat_fields &Heartbeat_msg
#define DeviceInfo_fields &DeviceInfo_msg
#define Hello_fields &Hello_msg
#define RequestDeviceInfo_fields &RequestDeviceInfo_msg
#define RequestCurrentPage_fields &RequestCurrentPage_msg
#define CurrentPage_fields &CurrentPage_msg
#define RequestElementAttribute_fields &RequestElementAttribute_msg
#define ElementAttributeState_fields &ElementAttributeState_msg

/* Maximum encoded size of messages (where known) */
#define AttributeChanged_size                    79
#define ButtonEvent_size                         20
#define CurrentPage_size                         12
#define DeviceInfo_size                          178
#define ElementAttributeState_size               33
#define ElementAttributeValue_size               51
#define ElementSnapshot_size                     536
#define Envelope_size                            8640
#define Heartbeat_size                           6
#define Hello_size                               181
#define InputEvent_size                          51
#define MACHINE_PB_H_MAX_SIZE                    Envelope_size
#define PageSnapshot_size                        8636
#define RequestCurrentPage_size                  6
#define RequestDeviceInfo_size                   6
#define RequestElementAttribute_size             20
#define SetElementAttribute_size                 69
#define ShowPage_size                            12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
