/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "machine.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Envelope, Envelope, 4)


PB_BIND(ShowPage, ShowPage, AUTO)


PB_BIND(PreparePage, PreparePage, AUTO)


PB_BIND(PagePrepared, PagePrepared, AUTO)


PB_BIND(ApplyPageData, ApplyPageData, 4)


PB_BIND(PageDataApplied, PageDataApplied, AUTO)


PB_BIND(CommitPage, CommitPage, AUTO)


PB_BIND(PageShown, PageShown, AUTO)


PB_BIND(AbortPreparedPage, AbortPreparedPage, AUTO)


PB_BIND(PageTransactionTimeout, PageTransactionTimeout, AUTO)


PB_BIND(TextChunk, TextChunk, AUTO)


PB_BIND(TextChunkAbort, TextChunkAbort, AUTO)


PB_BIND(SetElementAttribute, SetElementAttribute, AUTO)


PB_BIND(ElementAttributeValue, ElementAttributeValue, AUTO)


PB_BIND(ElementSnapshot, ElementSnapshot, 2)


PB_BIND(PageSnapshot, PageSnapshot, 4)


PB_BIND(AttributeChanged, AttributeChanged, AUTO)


PB_BIND(ButtonEvent, ButtonEvent, AUTO)


PB_BIND(InputEvent, InputEvent, AUTO)


PB_BIND(Heartbeat, Heartbeat, AUTO)


PB_BIND(DeviceInfo, DeviceInfo, AUTO)


PB_BIND(Hello, Hello, AUTO)


PB_BIND(RequestDeviceInfo, RequestDeviceInfo, AUTO)


PB_BIND(RequestCurrentPage, RequestCurrentPage, AUTO)


PB_BIND(CurrentPage, CurrentPage, AUTO)


PB_BIND(RequestElementAttribute, RequestElementAttribute, AUTO)


PB_BIND(ElementAttributeState, ElementAttributeState, AUTO)


