/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MACHINE_PB_H_INCLUDED
#define PB_MACHINE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Показать страницу по ID */
typedef struct _ShowPage {
    uint32_t page_id;
} ShowPage;

/* Установить текст элемента */
typedef struct _SetText {
    uint32_t element_id;
    char text[32]; /* макс. 64 символа (см. machine.options) */
} SetText;

/* Установить цвет элемента (RGB565, как в Nextion/LVGL) */
typedef struct _SetColor {
    uint32_t element_id;
    uint32_t bg_color; /* цвет фона */
    uint32_t fg_color; /* цвет текста/иконки */
} SetColor;

/* Показать или скрыть элемент */
typedef struct _SetVisible {
    uint32_t element_id;
    bool visible;
} SetVisible;

/* Числовое значение (прогресс-бар, чекбокс, слайдер и т.д.) */
typedef struct _SetValue {
    uint32_t element_id;
    int32_t value;
} SetValue;

/* Пакетное обновление — несколько операций за один кадр.
 Удобно когда нужно атомарно обновить целую страницу. */
typedef struct _SetBatch {
    pb_size_t texts_count;
    SetText texts[8];
    pb_size_t colors_count;
    SetColor colors[8];
    pb_size_t visibles_count;
    SetVisible visibles[8];
    pb_size_t values_count;
    SetValue values[8];
} SetBatch;

/* Нажатие кнопки или другого интерактивного элемента */
typedef struct _ButtonEvent {
    uint32_t element_id;
    uint32_t page_id; /* с какой страницы пришло событие */
} ButtonEvent;

/* Ввод данных пользователем (числовой input, поле текста) */
typedef struct _InputEvent {
    uint32_t element_id;
    uint32_t page_id;
    pb_size_t which_value;
    union {
        int32_t int_value;
        char string_value[32]; /* макс. 64 символа (см. machine.options) */
    } value;
} InputEvent;

/* Heartbeat — обе стороны шлют периодически для контроля связи */
typedef struct _Heartbeat {
    uint32_t uptime_ms; /* время работы отправителя в мс */
} Heartbeat;

/* Обёртка — всегда передаётся как payload в FrameCodec */
typedef struct _Envelope {
    pb_size_t which_payload;
    union {
        ShowPage show_page; /* показать страницу */
        SetText set_text; /* текст элемента */
        SetColor set_color; /* цвет фона и текста */
        SetVisible set_visible; /* видимость элемента */
        SetValue set_value; /* числовое значение (прогресс, чекбокс) */
        SetBatch set_batch; /* пакетное обновление нескольких полей */
        ButtonEvent button_event; /* нажатие кнопки (экран → контроллер) */
        InputEvent input_event; /* ввод значения пользователем */
        Heartbeat heartbeat; /* watchdog / детекция разрыва */
    } payload;
} Envelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Envelope_init_default                    {0, {ShowPage_init_default}}
#define ShowPage_init_default                    {0}
#define SetText_init_default                     {0, ""}
#define SetColor_init_default                    {0, 0, 0}
#define SetVisible_init_default                  {0, 0}
#define SetValue_init_default                    {0, 0}
#define SetBatch_init_default                    {0, {SetText_init_default, SetText_init_default, SetText_init_default, SetText_init_default, SetText_init_default, SetText_init_default, SetText_init_default, SetText_init_default}, 0, {SetColor_init_default, SetColor_init_default, SetColor_init_default, SetColor_init_default, SetColor_init_default, SetColor_init_default, SetColor_init_default, SetColor_init_default}, 0, {SetVisible_init_default, SetVisible_init_default, SetVisible_init_default, SetVisible_init_default, SetVisible_init_default, SetVisible_init_default, SetVisible_init_default, SetVisible_init_default}, 0, {SetValue_init_default, SetValue_init_default, SetValue_init_default, SetValue_init_default, SetValue_init_default, SetValue_init_default, SetValue_init_default, SetValue_init_default}}
#define ButtonEvent_init_default                 {0, 0}
#define InputEvent_init_default                  {0, 0, 0, {0}}
#define Heartbeat_init_default                   {0}
#define Envelope_init_zero                       {0, {ShowPage_init_zero}}
#define ShowPage_init_zero                       {0}
#define SetText_init_zero                        {0, ""}
#define SetColor_init_zero                       {0, 0, 0}
#define SetVisible_init_zero                     {0, 0}
#define SetValue_init_zero                       {0, 0}
#define SetBatch_init_zero                       {0, {SetText_init_zero, SetText_init_zero, SetText_init_zero, SetText_init_zero, SetText_init_zero, SetText_init_zero, SetText_init_zero, SetText_init_zero}, 0, {SetColor_init_zero, SetColor_init_zero, SetColor_init_zero, SetColor_init_zero, SetColor_init_zero, SetColor_init_zero, SetColor_init_zero, SetColor_init_zero}, 0, {SetVisible_init_zero, SetVisible_init_zero, SetVisible_init_zero, SetVisible_init_zero, SetVisible_init_zero, SetVisible_init_zero, SetVisible_init_zero, SetVisible_init_zero}, 0, {SetValue_init_zero, SetValue_init_zero, SetValue_init_zero, SetValue_init_zero, SetValue_init_zero, SetValue_init_zero, SetValue_init_zero, SetValue_init_zero}}
#define ButtonEvent_init_zero                    {0, 0}
#define InputEvent_init_zero                     {0, 0, 0, {0}}
#define Heartbeat_init_zero                      {0}

/* Field tags (for use in manual encoding/decoding) */
#define ShowPage_page_id_tag                     1
#define SetText_element_id_tag                   1
#define SetText_text_tag                         2
#define SetColor_element_id_tag                  1
#define SetColor_bg_color_tag                    2
#define SetColor_fg_color_tag                    3
#define SetVisible_element_id_tag                1
#define SetVisible_visible_tag                   2
#define SetValue_element_id_tag                  1
#define SetValue_value_tag                       2
#define SetBatch_texts_tag                       1
#define SetBatch_colors_tag                      2
#define SetBatch_visibles_tag                    3
#define SetBatch_values_tag                      4
#define ButtonEvent_element_id_tag               1
#define ButtonEvent_page_id_tag                  2
#define InputEvent_element_id_tag                1
#define InputEvent_page_id_tag                   2
#define InputEvent_int_value_tag                 3
#define InputEvent_string_value_tag              4
#define Heartbeat_uptime_ms_tag                  1
#define Envelope_show_page_tag                   1
#define Envelope_set_text_tag                    2
#define Envelope_set_color_tag                   3
#define Envelope_set_visible_tag                 4
#define Envelope_set_value_tag                   5
#define Envelope_set_batch_tag                   6
#define Envelope_button_event_tag                7
#define Envelope_input_event_tag                 8
#define Envelope_heartbeat_tag                   9

/* Struct field encoding specification for nanopb */
#define Envelope_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,show_page,payload.show_page),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_text,payload.set_text),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_color,payload.set_color),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_visible,payload.set_visible),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_value,payload.set_value),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_batch,payload.set_batch),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,button_event,payload.button_event),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,input_event,payload.input_event),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,heartbeat,payload.heartbeat),   9)
#define Envelope_CALLBACK NULL
#define Envelope_DEFAULT NULL
#define Envelope_payload_show_page_MSGTYPE ShowPage
#define Envelope_payload_set_text_MSGTYPE SetText
#define Envelope_payload_set_color_MSGTYPE SetColor
#define Envelope_payload_set_visible_MSGTYPE SetVisible
#define Envelope_payload_set_value_MSGTYPE SetValue
#define Envelope_payload_set_batch_MSGTYPE SetBatch
#define Envelope_payload_button_event_MSGTYPE ButtonEvent
#define Envelope_payload_input_event_MSGTYPE InputEvent
#define Envelope_payload_heartbeat_MSGTYPE Heartbeat

#define ShowPage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   page_id,           1)
#define ShowPage_CALLBACK NULL
#define ShowPage_DEFAULT NULL

#define SetText_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        1) \
X(a, STATIC,   SINGULAR, STRING,   text,              2)
#define SetText_CALLBACK NULL
#define SetText_DEFAULT NULL

#define SetColor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   bg_color,          2) \
X(a, STATIC,   SINGULAR, UINT32,   fg_color,          3)
#define SetColor_CALLBACK NULL
#define SetColor_DEFAULT NULL

#define SetVisible_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        1) \
X(a, STATIC,   SINGULAR, BOOL,     visible,           2)
#define SetVisible_CALLBACK NULL
#define SetVisible_DEFAULT NULL

#define SetValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        1) \
X(a, STATIC,   SINGULAR, INT32,    value,             2)
#define SetValue_CALLBACK NULL
#define SetValue_DEFAULT NULL

#define SetBatch_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  texts,             1) \
X(a, STATIC,   REPEATED, MESSAGE,  colors,            2) \
X(a, STATIC,   REPEATED, MESSAGE,  visibles,          3) \
X(a, STATIC,   REPEATED, MESSAGE,  values,            4)
#define SetBatch_CALLBACK NULL
#define SetBatch_DEFAULT NULL
#define SetBatch_texts_MSGTYPE SetText
#define SetBatch_colors_MSGTYPE SetColor
#define SetBatch_visibles_MSGTYPE SetVisible
#define SetBatch_values_MSGTYPE SetValue

#define ButtonEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   page_id,           2)
#define ButtonEvent_CALLBACK NULL
#define ButtonEvent_DEFAULT NULL

#define InputEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   element_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   page_id,           2) \
X(a, STATIC,   ONEOF,    INT32,    (value,int_value,value.int_value),   3) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,value.string_value),   4)
#define InputEvent_CALLBACK NULL
#define InputEvent_DEFAULT NULL

#define Heartbeat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_ms,         1)
#define Heartbeat_CALLBACK NULL
#define Heartbeat_DEFAULT NULL

extern const pb_msgdesc_t Envelope_msg;
extern const pb_msgdesc_t ShowPage_msg;
extern const pb_msgdesc_t SetText_msg;
extern const pb_msgdesc_t SetColor_msg;
extern const pb_msgdesc_t SetVisible_msg;
extern const pb_msgdesc_t SetValue_msg;
extern const pb_msgdesc_t SetBatch_msg;
extern const pb_msgdesc_t ButtonEvent_msg;
extern const pb_msgdesc_t InputEvent_msg;
extern const pb_msgdesc_t Heartbeat_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Envelope_fields &Envelope_msg
#define ShowPage_fields &ShowPage_msg
#define SetText_fields &SetText_msg
#define SetColor_fields &SetColor_msg
#define SetVisible_fields &SetVisible_msg
#define SetValue_fields &SetValue_msg
#define SetBatch_fields &SetBatch_msg
#define ButtonEvent_fields &ButtonEvent_msg
#define InputEvent_fields &InputEvent_msg
#define Heartbeat_fields &Heartbeat_msg

/* Maximum encoded size of messages (where known) */
#define ButtonEvent_size                         12
#define Envelope_size                            723
#define Heartbeat_size                           6
#define InputEvent_size                          45
#define MACHINE_PB_H_MAX_SIZE                    Envelope_size
#define SetBatch_size                            720
#define SetColor_size                            18
#define SetText_size                             39
#define SetValue_size                            17
#define SetVisible_size                          8
#define ShowPage_size                            6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
